### ISSUE TITLE
Nested parameters

### ISSUE THREAD

**Issue by ekampp** [k0kubun/rspec-openapi#13]
Hi there. 

First off, thanks for the great work. 

I'm currently looking into the various options for generating documentation using our existing specs as the base. 

It doesn't look like this library correctly respects the content type when generating parameters. Specifically, it doesn't [wrap the parameters as described here](https://swagger.io/docs/specification/describing-parameters/#schema-vs-content).

It currently generates this for `?filter[read]=false`:

```
parameters:
- name: filter
  in: query
  schema:
    type: object
    properties:
      read:
        type: string
  example:
  read: 'false'
```

I would expect it to generate this when the Content-Type and Accept headers indicate a JSON mimetype. 

```
parameters:
- name: filter
  in: query
  content:
    application/json:
      schema:
        type: object
        properties:
          read:
            type: string
      example:
        read: 'false'
```

Am I misunderstanding something? 

Best, 
Emil
